# permissions for end users to view endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: endpoint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-service-operator
    app.kubernetes.io/part-of: openstack-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: endpoint-viewer-role
rules:
- apiGroups:
  - identity.openstack.org
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.openstack.org
  resources:
  - endpoints/status
  verbs:
  - get
