apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: endpoints.identity.openstack.vexxhost.com
spec:
  group: identity.openstack.vexxhost.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                service:
                  type: string
                interface:
                  type: string
                  enum:
                    - public
                    - admin
                    - internal
                url:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: endpoints
    singular: endpoint
    kind: Endpoint
    shortNames:
      - ep
